output directory must already pre-exist
If 'foo' directory doesn't exist and you specify 'foo' here you get an error later on...

DNA Editing (delete): output
Traceback (most recent call last):
  File "./phyloGenerator.py", line 3790, in <module>
    main()
  File "./phyloGenerator.py", line 3736, in main
    currentState.dnaEditing()
  File "./phyloGenerator.py", line 2691, in dnaEditing
    mode, firstTime = deleteMode(firstTime)
  File "./phyloGenerator.py", line 2183, in deleteMode
    os.chdir(self.workingDirectory)
OSError: [Errno 2] No such file or directory: 'foo'